include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Error rules
    avoid_print: true
    avoid_relative_lib_imports: true
    avoid_slow_async_io: true
    cancel_subscriptions: true
    close_sinks: true
    valid_regexps: true
    
    # Style rules
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_single_quotes: true
    require_trailing_commas: false
    
    # Pub rules
    sort_pub_dependencies: true
    
    # Design
    use_key_in_widget_constructors: true
    sized_box_for_whitespace: true
    use_full_hex_values_for_flutter_colors: true
    
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
