// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbnRt9k9FmFTVPP7XFU4xZfZwGWni40_E',
    appId: '1:859909612284:web:3d9f67d78007e083a92d79',
    messagingSenderId: '859909612284',
    projectId: 'studio-6251333807-54897',
    authDomain: 'studio-6251333807-54897.firebaseapp.com',
    storageBucket: 'studio-6251333807-54897.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV40QkSFcHV9Bt0tyVo6yOZJXOZeZ1c_o',
    appId: '1:859909612284:android:1ecd1f9097678e21a92d79',
    messagingSenderId: '859909612284',
    projectId: 'studio-6251333807-54897',
    storageBucket: 'studio-6251333807-54897.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHyO_trMAbnJaEWxkR66wOT67pvoRSKVw',
    appId: '1:859909612284:ios:1296390941ee7d0da92d79',
    messagingSenderId: '859909612284',
    projectId: 'studio-6251333807-54897',
    storageBucket: 'studio-6251333807-54897.firebasestorage.app',
    androidClientId: '859909612284-h7ut1go2mkk48msov0i46f92ebo6koau.apps.googleusercontent.com',
    iosClientId: '859909612284-hhq524ofnljo464i2d8nahrb5rfbn2bv.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHyO_trMAbnJaEWxkR66wOT67pvoRSKVw',
    appId: '1:859909612284:ios:1296390941ee7d0da92d79',
    messagingSenderId: '859909612284',
    projectId: 'studio-6251333807-54897',
    storageBucket: 'studio-6251333807-54897.firebasestorage.app',
    androidClientId: '859909612284-h7ut1go2mkk48msov0i46f92ebo6koau.apps.googleusercontent.com',
    iosClientId: '859909612284-hhq524ofnljo464i2d8nahrb5rfbn2bv.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbnRt9k9FmFTVPP7XFU4xZfZwGWni40_E',
    appId: '1:859909612284:web:a89bed0de19d74b1a92d79',
    messagingSenderId: '859909612284',
    projectId: 'studio-6251333807-54897',
    authDomain: 'studio-6251333807-54897.firebaseapp.com',
    storageBucket: 'studio-6251333807-54897.firebasestorage.app',
  );
}